### ISSUE TITLE
reading ADC pin sometimes throws ValueError

### ISSUE THREAD

**Issue by letrout** [letrout/home_automation#20]
Published to influx/Owens/plants with PID 0
Traceback (most recent call last):
  File "code.py", line 106, in <module>
  File "code.py", line 95, in main
ValueError: ADC2 is being used by WiFi

**Comment by letrout** [comment]
fixed https://github.com/letrout/home_automation/pull/21

**Comment by letrout** [comment]
fixed https://github.com/letrout/home_automation/pull/21

**Comment by letrout** [comment]
Missed one:
Traceback (most recent call last):
  File "code.py", line 141, in <module>
  File "code.py", line 131, in main
  File "code.py", line 89, in wet_pct
  File "code.py", line 64, in dry_pct
ValueError: ADC2 is being used by WiFi

**Comment by letrout** [comment]
https://github.com/letrout/home_automation/pull/22
